school_list =[
"Admiralty Primary School",
"Ahmad Ibrahim Primary School",
"Ai Tong School",
"Alexandra Primary School",
"Anchor Green Primary School",
"Anderson Primary School",
"Ang Mo Kio Primary School",
"Anglo-Chinese School (Junior) - Boys only, Affiliated",
"Anglo-Chinese School (Primary) - Boys only, Affiliated",
"Angsana Primary School",
"Beacon Primary School",
"Bedok Green Primary School",
"Bendemeer Primary School",
"Blangah Rise Primary School",
"Boon Lay Garden Primary School",
"Bukit Panjang Primary School",
"Bukit Timah Primary School",
"Bukit View Primary School",
"Canberra Primary School",
"Canossa Catholic Primary School - Affiliated",
"Cantonment Primary School",
"Casuarina Primary School",
"Catholic High School - Boys only, Affiliated",
"Cedar Primary School",
"Changkat Primary School",
"CHIJ (Katong) Primary - Girls only, Affiliated",
"CHIJ (Kellock) - Girls only, Affiliated",
"CHIJ Our Lady of Good Counsel - Girls only, Affiliated",
"CHIJ Our Lady of the Nativity - Girls only, Affiliated",
"CHIJ Our Lady Queen of Peace - Girls only, Affiliated",
"CHIJ Primary (Toa Payoh) - Girls only, Affiliated",
"CHIJ St. Nicholas Girls’ School - Girls only, Affiliated",
"Chongfu School",
"Chongzheng Primary School",
"Chua Chu Kang Primary School",
"Clementi Primary School",
"Compassvale Primary School",
"Concord Primary School",
"Corporation Primary School",
"Damai Primary School",
"Dazhong Primary School",
"De La Salle School - Affiliated",
"East Spring Primary School",
"Edgefield Primary School",
"Elias Park Primary School",
"Endeavour Primary School",
"Eunos Primary School",
"Evergreen Primary School",
"Fairfield Methodist School (Primary) - Affiliated",
"Farrer Park Primary School",
"Fengshan Primary School",
"Fern Green Primary School",
"Fernvale Primary School",
"First Toa Payoh Primary School",
"Frontier Primary School",
"Fuchun Primary School",
"Fuhua Primary School",
"Gan Eng Seng Primary School",
"Geylang Methodist School (Primary) - Affiliated",
"Gongshang Primary School",
"Greendale Primary School",
"Greenridge Primary School",
"Greenwood Primary School",
"Guangyang Primary School",
"Haig Girls’ School - Girls only",
"Henry Park Primary School",
"Holy Innocents’ Primary School - Affiliated",
"Hong Wen School",
"Horizon Primary School",
"Hougang Primary School",
"Huamin Primary School",
"Innova Primary School",
"Jiemin Primary School",
"Jing Shan Primary School",
"Junyuan Primary School",
"Jurong Primary School",
"Jurong West Primary School",
"Juying Primary School",
"Keming Primary School",
"Kheng Cheng School",
"Kong Hwa School",
"Kranji Primary School",
"Kuo Chuan Presbyterian Primary School - Affiliated",
"Lakeside Primary School",
"Lianhua Primary School",
"Maha Bodhi School - Affiliated",
"Maris Stella High School - Boys only, Affiliated",
"Marsiling Primary School",
"Marymount Convent School - Girls only",
"Mayflower Primary School",
"Mee Toh School - Affiliated",
"Meridian Primary School",
"Methodist Girls’ School (Primary) - Girls only, Affiliated",
"Montfort Junior School - Boys only, Affiliated",
"Nan Chiau Primary School",
"Nan Hua Primary School",
"Nanyang Primary School - Affiliated",
"Naval Base Primary School",
"New Town Primary School",
"Ngee Ann Primary School - Affiliated",
"North Spring Primary School",
"North View Primary School",
"North Vista Primary School",
"Northland Primary School",
"Northoaks Primary School",
"Oasis Primary School",
"Opera Estate Primary School",
"Palm View Primary School",
"Park View Primary School",
"Pasir Ris Primary School",
"Paya Lebar Methodist Girls’ School (Primary) - Girls only, Affiliated",
"Pei Chun Public School",
"Pei Hwa Presbyterian Primary School",
"Pei Tong Primary School",
"Peiying Primary School",
"Pioneer Primary School",
"Poi Ching School",
"Princess Elizabeth Primary School",
"Punggol Cove Primary School",
"Punggol Green Primary School",
"Punggol Primary School",
"Punggol View Primary School",
"Qifa Primary School",
"Qihua Primary School",
"Queenstown Primary School",
"Radin Mas Primary School",
"Raffles Girls’ Primary School - Girls only",
"Red Swastika School",
"River Valley Primary School",
"Riverside Primary School",
"Rivervale Primary School",
"Rosyth School",
"Rulang Primary School",
"Sembawang Primary School",
"Seng Kang Primary School",
"Sengkang Green Primary School",
"Shuqun Primary School",
"Si Ling Primary School",
"Singapore Chinese Girls’ Primary School - Girls only, Affiliated",
"South View Primary School",
"Springdale Primary School",
"St. Andrew’s Junior School - Boys only, Affiliated",
"St. Anthony’s Canossian Primary School - Girls only, Affiliated",
"St. Anthony’s Primary School - Affiliated",
"St. Gabriel’s Primary School - Boys only, Affiliated",
"St. Hilda’s Primary School - Affiliated",
"St. Joseph’s Institution Junior - Boys only, Affiliated",
"St. Margaret’s School (Primary) - Girls only, Affiliated",
"St. Stephen’s School - Boys only, Affiliated",
"Stamford Primary School",
"Tampines North Primary School",
"Tampines Primary School",
"Tanjong Katong Primary School",
"Tao Nan School",
"Teck Ghee Primary School",
"Teck Whye Primary School",
"Telok Kurau Primary School",
"Temasek Primary School",
"Townsville Primary School",
"Unity Primary School",
"Waterway Primary School",
"Wellington Primary School",
"West Grove Primary School",
"West Spring Primary School",
"West View Primary School",
"Westwood Primary School",
"White Sands Primary School",
"Woodgrove Primary School",
"Woodlands Primary School",
"Woodlands Ring Primary School",
"Xinghua Primary School",
"Xingnan Primary School",
"Xinmin Primary School",
"Xishan Primary School",
"Yangzheng Primary School",
"Yew Tee Primary School",
"Yio Chu Kang Primary School",
"Yishun Primary School",
"Yu Neng Primary School",
"Yuhua Primary School",
"Yumin Primary School",
"Zhangde Primary School",
"Zhenghua Primary School",
"Zhonghua Primary School",
"Valour Primary School",
"Northshore Primary School",
]
